### ISSUE TITLE
Refactor: allow Dictationbridge to copy custom commands to a dictation software of user's choosing, not just limited to Dragon

### ISSUE THREAD

**Issue by josephsl** [dictationbridge/dictationbridge-nvda#5] opened 2017-02-17 21:16 UTC
Hi,

Part of a refactoring work:

one of the assumptions in DictationBridge is that only Dragon can include custom commands. It turns out one can define custom macros for Windows Speech Recognition (WSR; see issue #4) and one must copy the custom macro file to a special folder.

Thus I propose rewriting the dictation command copy routine as follows:

1. Rename "Install Dragon Commands" to "Install custom dictation commands".
2. Locate dictation software (WSR and/or Dragon).
3. In case of Dragon, let users select version in use (issue #3).
4. Copy custom commands (see issues #3 and #4 for details).

Thanks.

**Comment by derekriemer** [comment] 2017-07-21 15:10
The problem is the user might only want to install one engines commands. @josephsl Are you happy with the current addons submenu approach?

**Comment by josephsl** [comment] 2017-07-21 17:15
Hi, yes. Be mindful that NVDA Core 577 may change this a little bit later. Thanks.

**Comment by derekriemer** [comment] 2017-07-31 10:59
The implementation by @leonardder has the preferences menu still for addons to use. If all parties are happy with this, I'll close it.

**Closed as completed by derekriemer** 2017-07-31 10:59 UTC
